
DATA_FOLDER = "data"
CHROMA_FOLDER = "chroma_db"

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

LLM_MODEL_NAME = "llama-3.1-8b-instant"
TEMPERATURE = 0.2

CHUNK_SIZE = 800
CHUNK_OVERLAP = 100

TOP_K_RESULTS = 3
CONFIDENCE_THRESHOLD = 1.0
