name: Keep Streamlit App Awake
on:
  schedule:
    - cron: '0 */5 * * *
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -s https://ai-customer-support-copilot-ci5cnjkgcazqsub3fursgw.streamlit.app > /dev/null
